---
title: "ГЛАВА 2. МАТЕРИАЛЫ И МЕТОДЫ ИССЛЕДОВАНИЯ"
author: "Турбин К.О, Акулавев А.А., Повалий А.А."
date: ""
output: html_document
---
```{r, echo=FALSE}
library(openxlsx)
dfRadBillat<- read.xlsx(xlsxFile = "~/3dPlaning_RadiusOsteotomy/Луч Глава 5.xlsx",
                  sheet = '3')
dfRadProt<- read.xlsx(xlsxFile = "~/3dPlaning_RadiusOsteotomy/Луч Глава 5.xlsx",
                  sheet = '4')
dfRad<- read.xlsx(xlsxFile = "~/3dPlaning_RadiusOsteotomy/Луч Глава 5.xlsx",
                  sheet = '5')
```
## 2.1. Структура и общая характеристика диссертационного исследования

## 2.2. Первый этап экспериментальной части исследования
В этом исследовании изучались  `r length(dfRadBillat$ID)/2`  моделей для количественной оценки морфологии дистального метаэпифиза лучевой кости, включая стандартные измерения, обычно выполняемые клинически с использованием плоских двухмерных рентгенограмм. Все модели были сделаны на основании МСКТ  17  пациенов дистального метаэпифиза лучевой кости правой и левой руки. Исследовались пациенты без повреждения дистального метаэпифиза в анамнезе. Возрат пациентов, участвующих в исследовании был  45.53 ± 10.57  лет. Минимальный возраст участвовашего в исследовании был  30 , максимальный  65 . В исследовании было  24 ( 71 %) пациентов, занятых перимущественно умственным и смешанным типом труда, и  10 ( 29 %) пациентов, занятых перимущественно мануальным трудом.
## 2.3. Второй этап экспериментальной части исследования

## 3.3. Клиническая часть исследования
##